package testAM;

import fadak.base.TemplateAppModule;


import fadak.base.TemplateViewObject;

import oracle.jbo.Session;
import oracle.jbo.SessionData;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;

import oracle.jbo.server.ViewObjectImpl;

import org.parsisys.tehranuniversity.library.model.vo.LoanVOImpl;
import org.parsisys.tehranuniversity.library.model.vo.report.Rep_LanguagesVOImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 24 15:59:37 GMT+04:00 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestAppModImpl extends TemplateAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public TestAppModImpl() {
    }


    @Override
    public void prepareSession(SessionData sessionData) {
        super.prepareSession(sessionData);
    //TODO: this code must be change with the user actual labcol
      getSession().getUserData().put( "labcol" ,"1100" );
      //TODO: this code must be change with the actual username
      getSession().getUserData().put( "username" ,"testUser" );
        getSession().getUserData().put( "libartid" ,new Number(1) );
      getSession().getUserData().put( "validation_policy" ,"persian_cataloging" );
    }


    /**
     * Container's getter for LoanVO1.
     * @return LoanVO1
     */
    public LoanVOImpl getLoanVO1() {
        return (LoanVOImpl)findViewObject("LoanVO1");
    }

    /**
     * Container's getter for PhbookVbookVO1.
     * @return PhbookVbookVO1
     */
    public ViewObjectImpl getPhbookVbookVO1() {
        return (ViewObjectImpl)findViewObject("PhbookVbookVO1");
    }

    /**
     * Container's getter for Rep_LanguagesVO1.
     * @return Rep_LanguagesVO1
     */
    public Rep_LanguagesVOImpl getRep_LanguagesVO1() {
        return (Rep_LanguagesVOImpl)findViewObject("Rep_LanguagesVO1");
    }

    /**
     * Container's getter for DepartmentVO1.
     * @return DepartmentVO1
     */
    public ViewObjectImpl getDepartmentVO1() {
        return (ViewObjectImpl)findViewObject("DepartmentVO1");
    }
}
